### ISSUE TITLE
I'll wait for a newer release

### ISSUE THREAD

**Issue by joelcnz** [TodNaz/Foxid#19]
(no question, or, maybe, when is the next release?)

I'm not getting very far with 'Image' class (either crashes with 'fromTexture'), so I think I'll wait for a newer version of Foxid. I've gotten somewhere with text with fonts, but game text (using png files to get the characters) uses 'Image'.
```
(FoxidVersion: 0.3) 
Assertion failed: (_Unwind_Resume() can't return), function _Unwind_Resume, file /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/libunwind/libunwind-35.4/src/UnwindLevel1.c, line 320.
Program exited with code -6
```

**Comment by TodNaz** [comment]
It is not necessary to wait for a new release, you can take the `master` branch if the build via CI was successful. I've already fixed the bugs.

**Comment by joelcnz** [comment]
I tried 'dub upgrade' with ~master, but I still get that above error! Including just '0.3'

**Comment by TodNaz** [comment]
Strange, I checked by creating a project under `master` and everything was fine.

How did you add? So?
`$ dub add foxid=~master`

Or did your project build fail?

**Comment by joelcnz** [comment]
I've tried 'dub add ..' It does build. I tried Windows, and got other errors.

This line doesn't work:
```d
	foreach(ref e; sprites) e.fromTexture;
```

**Comment by TodNaz** [comment]
Can you tell me what the mistakes are? It's just that everything is going to me.

**Comment by joelcnz** [comment]
```d
	immutable spritesFileName = "RockDashColoured.png";
	import std.file : exists;
	assert(spritesFileName.exists, "File not found");
	Image[] sprites = loader.load!ImageSurface(spritesFileName).imageHandle.strip(Vec(0,0), 24, 24);
	assert(sprites, "sprites failed");

	foreach(ref e; sprites) e.fromTexture; //#crashes
```
If I take out the 'foreach' line, the graphics don't show.

**Comment by joelcnz** [comment]
![RockDashColoured](https://user-images.githubusercontent.com/653293/95671196-689b5900-0bf0-11eb-80a8-40bce1d45c80.png)

**Comment by TodNaz** [comment]
Very strange. I tested your code and it worked. 
```D
class Test : Scene
{
    Image[] sprites;

    this() @safe
    {
        sprites = loader.load!ImageSurface("test.png").imageHandle.strip(Vec(0,0), 24, 24);
        foreach(ref e; sprites) e.fromTexture;
    }

    override void draw(Display graph) @safe
    {
        foreach(size_t i; 0 .. sprites.length) {
            graph.draw(sprites[i],Vec(i * 24,i * 24));
        }
    }
}
```
Do you have data segmentation or exception?

**Comment by joelcnz** [comment]
My code isn't in a Scene class.

**Comment by TodNaz** [comment]
Um ... do you create this after the window is created? I just can't imagine how there could be a mistake in such a place. If you don't use `game.d`, do you create managers, windows and the like?

**Comment by TodNaz** [comment]
> It works with a Scene class, but I don't want it in one. Can I load the graphics another way?

Give more information, I don't really understand where and how you use it. I'm not a fortune teller.

**Comment by joelcnz** [comment]
I used this setup function from my stuff:
```d
bool jf_setup(in string title = "Jec Foxid", int windowWidth = 640, int windowHeight = 480, Color clearColour = Color(0,0,0)) @trusted {
	sdlInit(); // Initialize sdl 2.
	_foxloader = new Loader();
	_foxscene = new SceneManager();
	//_listener = new Listener();
	_window = new Window();
	_window.create(windowWidth,windowHeight,title);
	_window.background = clearColour; //Clr.black;
	gWin = _window;
	gGraph = new Display(gWin); // We create and tell the display that we are drawing into this window.
	assert(jf_initKeys, "keys failure");
	gFont = new Font();
	immutable fontFileName = "fonts/DejaVuSans.ttf";
	gFont.load(fontFileName,gFontSize);
	guiSetup;

	return true;
}
```

**Comment by TodNaz** [comment]
I use this and everything worked:
```D
int main(string[] args) @trusted
{
    sdlInit(); // Initialize sdl 2.
    Event event;
    _foxloader = new Loader();
    _foxscene = new SceneManager();
    //_listener = new Listener();
    _window = new Window();
    _window.create(640,480,"Foxid");
    _window.background = Clr.white; //Clr.black;

    Display graph = new Display(window);

    Image[] sprites = loader.load!ImageSurface("test.png").imageHandle.strip(Vec(0,0), 24, 24);
    foreach(ref e; sprites) e.fromTexture;

    bool isGame = true;
    while(isGame) {
        while(event.update) {
            if(event.isQuit) isGame = false;
        }

        graph.clear();
        foreach(size_t i; 0 .. sprites.length) {
            graph.draw(sprites[i],Vec(i * 24,i * 24));
        }
        graph.drawning();
    }

    return 0;
}
```

Go through the debugger, or do the following checks:
```D
assert(window !is null);
assert(window.sdlWindow !is null);
assert(window.sdlRender !is null);
assert(_foxloader !is null);
```

**Comment by joelcnz** [comment]
Yeah, your code worked at my end too.

**Comment by TodNaz** [comment]
It means that something is already wrong on your side. Do checks and the like.

**Comment by joelcnz** [comment]
I can't seem to get 'copy' and 'blit' working:
```d
auto sprite = new Image();
sprite.create(w,h);
sprite = sprites[1].copy(Vec(0,0),w,h);
auto stamp = new Image();
stamp.create(gWin.width,gWin.height);
sprite.blit(stamp,Vec(100,50));
gGraph.draw(stamp,Vec(0,0));
```
I  want to have a buffer to draw onto with updating (text editor, when you press a key it updates the buffer, otherwise just draws the buffer).

**Comment by TodNaz** [comment]
And what's incomprehensible? Just re-create the buffer. For example, you can see an example implementation here: https://github.com/TodNaz/Foxid/blob/master/source/foxid/type/text.d#L213

**Comment by joelcnz** [comment]
I mean, with picture files:

![lemblue](https://user-images.githubusercontent.com/653293/95690647-b312e900-0c75-11eb-8a53-a59104561ff9.png)

I've done it in the past with DSFML, and SDL. I just edit the old stuff - converting it.

I'm at the testing stage with Foxid, and it's not working.

**Comment by TodNaz** [comment]
```D
// Context create

Image[] text = loader.load!ImageSurface("lemblue.png").imageHandle.strip(Vec(0,0),charW,charH)[0 .. $-1];

// ...

Image stampArea = new Image();
stampArea.create(window.width/2, window.height/2, Color(0,0,0,255),PixelFormat.RGBA); // or PixelFormat.RGB

int x;
"Joel Ezra Christensen".each!((l) {
    auto letSquare = Vec(x*9,0);
    // image, position, width, height
    stampArea.blit(text[l],letSquare,9,16);

});

stampArea.fromTexture();

// ...
graph.clear();
graph.draw(stampArea,Vec(32,32));
graph.drawning();

// ...
stampArea.free();
// ...
```

**Comment by TodNaz** [comment]
In [this](https://github.com/TodNaz/Foxid/commit/1002d0e48fe913e88d8fcd8ceececa2e08ac8a02) , I rendered the texture directly, thanks for the idea:
```D
// Context create

Image[] text = loader.load!ImageSurface("lemblue.png").imageHandle.strip(Vec(0,0),charW,charH)[0 .. $-1];
text.each!((e) => e.fromTexture());

// ...

Image stampArea = new Image();
stampArea.createTexture(window.width/2, window.height/2, Color(0,0,0,255),PixelFormat.RGBA); // or PixelFormat.RGB

stampArea.edit((Display graph) {
    int x;
    "Joel Ezra Christensen".each!((l) {
        auto letSquare = Vec(x*9,0);
        // image, position, width, height
        graph.draw(text[l],Vec(x*9,0);
        x++;
    });
});

// ...
graph.clear();
graph.draw(stampArea,Vec(32,32));
graph.drawning();

// ...
stampArea.free();
// ...
```

**Comment by joelcnz** [comment]
What's '[0 .. $-1]' for? (Image[] text = loader.load!ImageSurface("lemblue.png").imageHandle.strip(Vec(0,0),charW,charH)[0 .. $-1];)

**Comment by TodNaz** [comment]
It just might have a blank texture at the end.

**Comment by joelcnz** [comment]
It always crashes without '[0..$-1]', and I've tried changing the the picture file.
![lemblue](https://user-images.githubusercontent.com/653293/95926547-12f5c500-0e19-11eb-85e4-aca9f26ba3d8.png)

**Comment by TodNaz** [comment]
Through the display module, is it possible to draw directly with an alpha channel. You can do this with an RGBA pixel texture, or surfboard, and draw a square or whatever.
Example:
```D
Image img = new Image();
img.create(64,64,PixelFormat.RGBA); // surface
foreach(ix; 0 .. 64) 
    foreach(iy; 0 .. 64)
        img.setPixel(ix,iy,Color(0,0,255,128));

img.fromTexture();
```

**Comment by joelcnz** [comment]
What?! Can't you use 'SDL_SetRenderDrawBlendMode'?

Have you seen? blackbird806: Hey there, I translated SDL2gfx_primitives from SDL_gfx Library to D. https://github.com/blackbird806/SDL2_gfxPrimitives-D

The following code doesn't work much, seems to show the dimentions, but not reclaim memory or anything:
```d
module jecfoxid.draw;

import jecfoxid;

struct JRectangle {
    Vec pos, size;
    Color col;
    BoxStyle boxStyle;
    bool trans;
    Image block;

    this(SDL_Rect rect, BoxStyle boxStyle, SDL_Color col, bool trans = false) {
        this.pos = Vec(rect.x,rect.y);
        this.size = Vec(rect.w,rect.h);
        this.boxStyle = boxStyle;
        this.col = Color(col.r,col.g,col.b,col.a);
        this.trans = trans;
        if (boxStyle==BoxStyle.solid && trans) {
            block = new Image();
            mixin(tce("/*JRectangle*/rect.w rect.h".split));
            block.create(rect.w,rect.h,this.col,PixelFormat.RGBA);
            /+ foreach(ix; 0f .. cast(float)block.width) 
                foreach(iy; 0f .. cast(float)block.height)
                    block.setPixel(Vec(ix,iy),this.col); +/
            block.fromTexture();
        }
    }

    ~this()  {
        if (block) {
            "free".gh;
            block.free();
        }
    }

    void draw(Display graph) {
        if (boxStyle==BoxStyle.outLine || ! trans) {
            graph.drawRect(pos,pos+size,col,boxStyle==BoxStyle.solid);
        } else {
            "draw".gh;
            graph.draw(block,pos);
        }
    }
}
```

**Comment by TodNaz** [comment]
In the last commit I added this to the render. Now, you can set the blend mod in the texture or render:
```D
window.blendMode = BlendMode.blend;
// graph alpha channel...
...
window.blendMode = BlendMode.none;
```

**Comment by TodNaz** [comment]
I think the question is settled.
